# Dependabot configuration for Expense Tracker monorepo
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Root workspace dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "manastalukdar"
    commit-message:
      prefix: "deps(root)"
      include: "scope"

  # Mobile app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "manastalukdar"
    commit-message:
      prefix: "deps(mobile)"
      include: "scope"

  # Shared package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "manastalukdar"
    commit-message:
      prefix: "deps(shared)"
      include: "scope"

  # Database package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/database"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "manastalukdar"
    commit-message:
      prefix: "deps(database)"
      include: "scope"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "manastalukdar"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"

  # Android Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/apps/mobile/android"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "manastalukdar"
    commit-message:
      prefix: "deps(android)"
      include: "scope"
